[package]
name = "gicv2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tock-registers = "0.8"
critical-section = "1"

[dependencies.bitvec]
version = "1"
default-features = false
